{
 "title": "Apache Camel - Context view",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(camel_routes_running_routes{eventType=\"RouteEvent\"},job)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(camel_routes_running_routes{eventType=\"RouteEvent\",job=~\"${job}\"},namespace)"
    }
   },
   {
    "name": "context",
    "label": "Camel Context",
    "query": {
     "query": "label_values(camel_routes_running_routes{eventType=\"RouteEvent\",job=~\"${job}\",namespace=\"$namespace\"},camelContext)"
    }
   },
   {
    "name": "route",
    "label": "Camel Route",
    "query": {
     "query": "label_values(camel_exchanges_succeeded_total{job=~\"${job}\",namespace=\"$namespace\",camelContext=\"$context\"},routeId)"
    }
   },
   {
    "name": "processor",
    "label": "Camel Processor",
    "query": {
     "query": "label_values(camel_message_history_seconds_count{job=~\"${job}\",namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"},nodeId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global Stats Camel Context : $context",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Routes Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (\n    camel_routes_running_routes{\n        job=~\"$job\",\n        namespace=\"$namespace\",\n        camelContext=\"$context\"})",
     "legendFormat": "Instances"
    },
    {
     "expr": "sum(\n    camel_routes_running_routes{\n        job=~\"$job\",\n        namespace=\"$namespace\",\n        camelContext=\"$context\"}) \n/ \nsum(\n    camel_routes_added_routes{\n        job=~\"$job\",\n        namespace=\"$namespace\",\n        camelContext=\"$context\"})\n*\n100",
     "legendFormat": "Running"
    },
    {
     "expr": "max(\n    camel_routes_added_routes{\n        job=~\"$job\",\n        namespace=\"$namespace\",\n        camelContext=\"$context\"})",
     "legendFormat": "Routes"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "stat",
   "description": "Shows completed exchanges of the camel context in the time range",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    increase(\n        camel_exchanges_total{\n            job=~\"$job\",\n            namespace=\"$namespace\",\n            camelContext=\"$context\"}[$__range]\n    )\n)"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (camelContext) (\n    increase(\n        camel_exchanges_failed_total{\n            job=~\"$job\",\n            namespace=\"$namespace\",\n            camelContext=\"$context\"}[$__range]\n    )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (camelContext) (\n    increase(\n        camel_exchanges_failed_total{\n            job=~\"$job\",\n            namespace=\"$namespace\",\n            camelContext=\"$context\"}[$__range])\n    ) \n/ \nsum by (camelContext) (\n    increase(\n        camel_exchanges_total{\n            job=~\"$job\",\n            namespace=\"$namespace\",\n            camelContext=\"$context\"}[$__range]\n    )\n)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saturation : CPU Usage by node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(node) (\n    process_cpu_usage{\n        job=~\"$job\",\n        namespace=\"$namespace\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Saturation : Memory usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n    jvm_memory_used_bytes{\n        job=~\"$job\",\n        namespace=\"$namespace\",\n        area=\"heap\"\n    }) \n/ \nsum by (pod) (\n    jvm_memory_max_bytes{\n        job=~\"$job\",\n        namespace=\"$namespace\",\n        area=\"heap\"\n    })",
     "legendFormat": "{{pod}} heap"
    },
    {
     "expr": "sum by (pod) (\n    jvm_memory_used_bytes{\n        job=~\"$job\",\n        namespace=\"$namespace\",\n        area=\"nonheap\"\n    }) \n/ \nsum by (pod) (\n    jvm_memory_max_bytes{\n        job=~\"$job\",\n        namespace=\"$namespace\",\n        area=\"nonheap\"\n    })",
     "legendFormat": "{{pod}} nonheap"
    }
   ]
  },
  {
   "title": "Pods per Nodes and CPU Usage",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "count by (node) (\n    camel_routes_running_routes{\n        job=~\"$job\",\n        namespace=\"$namespace\",\n        camelContext=\"$context\"})\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (node) (\n    process_cpu_usage{\n        job=~\"$job\",\n        namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inflight",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    camel_exchanges_inflight{\n        job=~\"$job\",\n        namespace=\"$namespace\",\n        camelContext=\"$context\"})"
    }
   ]
  },
  {
   "title": "Camel Context Overview - RED Method",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Rate : Executions / sec",
   "type": "stat",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (routeId) (\n    irate(\n        camel_exchanges_total{\n            job=~\"$job\",\n            namespace=\"$namespace\",\n            camelContext=\"$context\",\n            routeId=~\"$route\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Duration : Avg Execution time",
   "type": "stat",
   "gridPos": { "h": 13, "w": 9, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (routeId) (\n    increase (\n        camel_route_policy_seconds_sum{\n            job=~\"$job\",\n            namespace=\"$namespace\",\n            camelContext=\"$context\",\n            routeId=~\"$route\"\n        }[$__range]\n    )\n) \n \n/ \n \nsum by (routeId) (\n    increase (\n        camel_route_policy_seconds_count{\n            job=~\"$job\",\n            namespace=\"$namespace\",\n            camelContext=\"$context\",\n            routeId=~\"$route\"\n        }[$__range]\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors : Failure Rates",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (routeId) (\n    increase(\n        camel_exchanges_failed_total{\n            job=~\"$job\",\n            namespace=\"$namespace\",\n            camelContext=\"$context\",\n            routeId=~\"$route\"\n        }[$__range]\n    )\n) \n/ \nsum by (routeId) (\n    increase(\n        camel_exchanges_total{\n            job=~\"$job\",\n            namespace=\"$namespace\",\n            camelContext=\"$context\",\n            routeId=~\"$route\"\n        }[$__range]\n    ) > 0\n)",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Traffic Per Route",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Ex/sec",
     "type": "stat",
     "description": "Show the numbers of exchanges per second for camel route $route",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 22 },
     "repeat": "route",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(\n    irate(\n        camel_exchanges_total{\n            job=~\"$job\",\n            namespace=\"$namespace\",\n            camelContext=\"$context\",\n            routeId=~\"$route\"\n        }[$__rate_interval]\n    )\n)"
      }
     ]
    },
    {
     "title": "$route Exchanges/sec - all instances",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 5, "x": 2, "y": 22 },
     "repeat": "route",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (camelContext) (\n    irate(\n        camel_exchanges_total{\n            job=~\"$job\",\n            namespace=\"$namespace\",\n            camelContext=\"$context\",\n            routeId=~\"$route\"\n        }[$__rate_interval]\n    )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$route  Exchanges/sec - per instances",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 5, "x": 7, "y": 22 },
     "repeat": "route",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n    irate(\n        camel_exchanges_total{\n            job=~\"$job\",\n            namespace=\"$namespace\",\n            camelContext=\"$context\",\n            routeId=~\"$route\"\n        }[$__rate_interval]\n    )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$route Failure % - all instances",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 5, "x": 12, "y": 22 },
     "repeat": "route",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (routeId) (\n    increase(\n        camel_exchanges_failed_total{\n            job=~\"$job\",\n            namespace=\"$namespace\",\n            camelContext=\"$context\",\n            routeId=~\"$route\"\n        }[$__range]\n    )\n) \n/ \nsum by (routeId) (\n    increase(\n        camel_exchanges_total{\n            job=~\"$job\",\n            namespace=\"$namespace\",\n            camelContext=\"$context\",\n            routeId=~\"$route\"\n        }[$__range]\n    )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Inflight $route",
     "type": "stat",
     "description": "Current number of inflight exchanges",
     "gridPos": { "h": 5, "w": 2, "x": 17, "y": 22 },
     "repeat": "route",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (camelContext) (\n    camel_exchanges_inflight{\n        job=~\"$job\",\n        namespace=\"$namespace\",\n        camelContext=\"$context\",\n        routeId=~\"$route\"\n    })",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$route Inflight  - per instances",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 22 },
     "repeat": "route",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (kubernetes_pod_name) (camel_exchanges_inflight{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"})",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Execution Times Per Route",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Avg Exec time $route",
     "type": "stat",
     "description": "Average execution time for a route",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 23 },
     "repeat": "route",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (camelContext) (\n    increase (\n        camel_route_policy_seconds_sum{\n            job=~\"$job\",\n            namespace=\"$namespace\",\n            camelContext=\"$context\",\n            routeId=~\"$route\"\n        }[$__range]\n    )\n) \n\n/ \n\nsum by (camelContext) (\n    increase (\n        camel_route_policy_seconds_count{\n            job=~\"$job\",\n            namespace=\"$namespace\",\n            camelContext=\"$context\",\n            routeId=~\"$route\"\n        }[$__range]\n    )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg Exec time $route - all instances",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 5, "x": 2, "y": 23 },
     "repeat": "route",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (camelContext) (\n    increase (\n        camel_route_policy_seconds_sum{\n            job=~\"$job\",\n            namespace=\"$namespace\",\n            camelContext=\"$context\",\n            routeId=~\"$route\"\n        }[$__range]\n    )\n) \n \n/ \n \nsum by (camelContext) (\n    increase (\n        camel_route_policy_seconds_count{\n            job=~\"$job\",\n            namespace=\"$namespace\",\n            camelContext=\"$context\",\n            routeId=~\"$route\"\n        }[$__range]\n    )\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg Exec time $route - per instances",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 5, "x": 7, "y": 23 },
     "repeat": "route",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n    increase (\n        camel_route_policy_seconds_sum{\n            job=~\"$job\",\n            namespace=\"$namespace\",\n            camelContext=\"$context\",\n            routeId=~\"$route\"\n        }[$__range]\n    )\n) \n \n/ \n \nsum by (pod) (\n    increase (\n        camel_route_policy_seconds_count{\n            job=~\"$job\",\n            namespace=\"$namespace\",\n            camelContext=\"$context\",\n            routeId=~\"$route\"\n        }[$__range]\n    )\n)",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Processor Execution Times - $route",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
     "repeat": "route",
     "targets": [
      {
       "expr": "sum by (routeId,nodeId) (\n    increase (\n        camel_message_history_seconds_sum{\n            job=~\"$job\",\n            namespace=\"$namespace\",\n            camelContext=\"$context\",\n            routeId=~\"$route\",\n            nodeId=~\"$processor\"\n        }[$__range]\n    )\n) \n/ \nsum by (routeId,nodeId) (\n    increase (\n        camel_message_history_seconds_count{\n            job=~\"$job\",\n            namespace=\"$namespace\",\n            camelContext=\"$context\",\n            routeId=~\"$route\",\n            nodeId=~\"$processor\"\n        }[$__range]\n    )\n)\n"
      }
     ]
    }
   ]
  }
 ]
}